### ISSUE TITLE
Any guide for this plugin?

### ISSUE THREAD

**Issue by Zkffkah** [thetruejacob/memorize-anki#2] opened 2020-11-20 06:26 UTC
This plugin looks interesting. Is there any guide for me to use it?

**Comment by thetruejacob** [comment] 2020-11-27 15:07
Not really. Just implement it and the scheduling algorithm should work immediately on the backend. It might mess up your database though, so maybe use it on a separate account. It works by tricking the backend about the review history of the cards to get the desired review date to show up properly.

**Comment by Zkffkah** [comment] 2020-11-28 08:37
So it overrid the sched method, and the default options won't take effect. But how do I verify the ebisu algo had take effect? For example, for a new card, what's the correct review date if I click pass, etc.

**Comment by thetruejacob** [comment] 2020-11-28 15:36
You'll be able to tell as soon as you use it. The next review dates might be a little unintuitive.

**Comment by thetruejacob** [comment] 2020-11-28 16:51
I tested this out - it's definitely working but there's a bug - fresh cards get assigned to 2 years after. Not sure what the problem is here.

**Comment by thetruejacob** [comment] 2020-11-28 19:10
It works now - more or less. The 'next due dates' on the answer buttons don't work properly, though.

**Closed as completed** 2020-11-29 05:32 UTC
